title: DNHS Flocker
description: "Social Media for Del Norte High School"
owner_name: John Mortensen
github_username: nighthawkcoders
github_repo: "flocker_frontend" 
baseurl: "/flocker_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/travel/destination_imagination/destination_main.md